apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: analytics
    user: analytics
    secureJsonData:
      password: 'analytics123'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
